### ISSUE TITLE
Cache Invalidate

### ISSUE THREAD

**Issue by kurian86** [micronaut-projects/micronaut-redis#124]
### Steps to Reproduce

Use the following annotation to invalidate the entire cache `@CacheInvalidate(all = true, async = true)`

### Expected Behaviour

Delete all cache keys without errors

### Actual Behaviour

If there are no keys in redis, an error occurs.

```
16:32:01.251 [io-executor-thread-2] ERROR i.m.c.interceptor.CacheInterceptor - Error invalidating cache: event
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Keys must not be empty
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1081)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:109)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:680)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:640)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:591)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Keys must not be empty
	at io.lettuce.core.internal.LettuceAssert.notEmpty(LettuceAssert.java:100)
	at io.lettuce.core.RedisCommandBuilder.notEmpty(RedisCommandBuilder.java:3272)
	at io.lettuce.core.RedisCommandBuilder.del(RedisCommandBuilder.java:544)
	at io.lettuce.core.AbstractRedisAsyncCommands.del(AbstractRedisAsyncCommands.java:428)
	at io.micronaut.configuration.lettuce.cache.RedisCache$RedisAsyncCache.deleteByKeys(RedisCache.java:391)
	at io.micronaut.configuration.lettuce.cache.RedisCache$RedisAsyncCache.lambda$invalidateAll$5(RedisCache.java:386)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	... 23 common frames omitted
```

### Environment Information

- **Operating System**: Windows
- **Micronaut Version:** 2.1.0
- **JDK Version:** 11

**Comment by sdelamo** [comment]
I think this was already solved via https://github.com/micronaut-projects/micronaut-redis/commit/2be6eb5455a1058d9c5f9c797a70d7d663696b67
