### ISSUE TITLE
Upgrade from 2.3.3 to 2.4.1 cannot deploy to GCP with Google Redis Memorystore

### ISSUE THREAD

**Issue by lex-erik** [micronaut-projects/micronaut-redis#179]
Hi all, I've bumped all versions to 2.4.1. I'm deploying to GCP and I'm making use of Redis Google Memory Store.

In Application.yml:

```
redis:
  uri: "${REDIS_URL:`redis://localhost`}"
```
where REDIS_URL is redis://x.x.x.x

The application refuses to start with a Redis error:
```
ERR unknown command `CLIENT`, with args beginning with: `SETNAME`, `application
```

I found a [Gitlabhq commit](https://github.com/gitlabhq/omnibus-gitlab/commit/73f963289ea091c7bb454257cc2114cc235ab456#diff-bc1448597383861719a04b6ffcbf439a6f42a27b0b8c575001a1da580b21966eR22
) mentioning the same issue. It states:
```
Google Cloud Memorystore [does not support the Redis CLIENT
command.]
```

Reverting Micronaut parent back to 2.3.3 "fixes" it.

Full stack trace:
```
Path Taken: DoubleBookingRepository.connection
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1970)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2710)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2382)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2356)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1261)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1699)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1456)
	at xxx.external.calendar.$DoubleBookingRepositoryDefinition.injectBean(Unknown Source)
	at xxx.external.calendar.$DoubleBookingRepositoryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2724)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2260)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1559)
	... 6 common frames omitted
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to 10.155.159.51/<unresolved>:6379
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:320)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:211)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:196)
	at io.micronaut.configuration.lettuce.AbstractRedisClientFactory.redisConnection(AbstractRedisClientFactory.java:70)
	at io.micronaut.configuration.lettuce.DefaultRedisClientFactory.redisConnection(DefaultRedisClientFactory.java:55)
	at io.micronaut.configuration.lettuce.$DefaultRedisClientFactory$RedisConnection1Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	... 19 common frames omitted
Caused by: io.lettuce.core.RedisCommandExecutionException: ERR unknown command `CLIENT`, with args beginning with: `SETNAME`, `application`,
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:137)
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:110)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:720)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:655)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:572)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by lex-erik** [comment]
I'd like to highlight that, as far as I now understand, micronaut-redis no longer works on _any_ GCP setup. For whoever is blocked by this, please see a workaround below.

---
It seems that the Lettuce RedisClient doesn't require the `clientName` to be set. Micronaut is actively checking and double checking if the application is null, and will default to "application" (from Environment) if that's the case.

My current workaround looks like this:
```
import io.lettuce.core.RedisURI;
import io.micronaut.configuration.lettuce.AbstractRedisConfiguration;
import io.micronaut.configuration.lettuce.DefaultRedisConfiguration;
import io.micronaut.configuration.lettuce.RedisSetting;
import io.micronaut.context.annotation.ConfigurationProperties;
import io.micronaut.context.annotation.Primary;
import io.micronaut.context.annotation.Replaces;
import io.micronaut.context.annotation.Requires;

@ConfigurationProperties(RedisSetting.PREFIX)
@Primary
@Requires(property = RedisSetting.PREFIX)
@Replaces(DefaultRedisConfiguration.class)
public class WorkaroundRedisConfiguration extends AbstractRedisConfiguration {
    /**
     * As a workaround for micronaut-redis issue.
     * 
     * https://github.com/micronaut-projects/micronaut-redis/issues/179
     */
    public WorkaroundRedisConfiguration() {
        setClientName(null);
        setPort(RedisURI.DEFAULT_REDIS_PORT);
        setHost("localhost"); // localhost by default
    }
}

```

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-redis/pull/177
