### ISSUE TITLE
Server freezes after hitting /health endpoint

### ISSUE THREAD

**Issue by chrisparton1991** [micronaut-projects/micronaut-redis#184]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the repo
```
git clone git@github.com:chrisparton1991/micronaut-redis-session-lockup.git
```
2. Launch a local Redis instance
```
docker pull redis:6.2.1
docker run --publish 6379:6379 redis:6.2.1
```
3. Launch the Micronaut server
```
./gradlew run
```
4. Repeatedly hit the `/health` endpoint with a session (doesn't have to be a valid session)
```
 curl -H "X-Auth-Token: foo" http://localhost:8080/health
```

### Expected Behaviour

The health endpoint should return a JSON response every time, with no disruption to service.

### Actual Behaviour

Eventually (seems like on the 8th call for this example), the endpoint stops responding. The endpoint will only respond if it doesn't need to communicate with Redis, e.g. by removing the `X-Auth-Token` header from the curl request.

Authenticated calls no longer return any response, effectively locking out all authenticated users.

### Environment Information

- **Operating System**: Windows 10 Pro (also reproduced on Linux in an Azure App Service)
- **Micronaut Version:** 2.4.2
- **JDK Version:** Zulu JDK 11.0.7 and AdoptOpenJdk 11.0.7

### Example Application
The application is a barebones project generated using Micronaut Launch with the following settings:
![launch](https://user-images.githubusercontent.com/13063119/113823520-1794a800-97c2-11eb-88fc-18e3d6d2d7c4.png)

The second commit to the repo includes all necessary 
**Repo URL:**
https://github.com/chrisparton1991/micronaut-redis-session-lockup

**Video demonstrating lockup:**
https://imgur.com/a/8ViC4sa

**Comment by graemerocher** [comment]
Possibly caused by https://github.com/micronaut-projects/micronaut-redis/commit/398e6d5f8cbaddb3e05497c4a91ea303e12cf2d0

**Comment by graemerocher** [comment]
@pgressa can you check?

**Comment by chrisparton1991** [comment]
Thanks for the quick response @graemerocher.

I tried updating to the latest `micronaut-redis-lettuce` using `implementation("io.micronaut.redis:micronaut-redis-lettuce:4.0.1")` but the issue still persists.

**Comment by chrisparton1991** [comment]
To add some context, I noticed that a production server was occasionally locking up due to a Redis connection failure. A restart always fixes the issue so it doesn't seem like the Redis server is the issue. Not ruling anything out at this point though.

To work around the lockup, I configured a regular ping to `/health` to detect a Redis issue and automatically restart the server. This is when I found that the health endpoint could also lock up the server. It's possible these are two symptoms of an underlying problem.

I'll continue to investigate from my end.

Stack trace from the original problem:
```
2021-04-05T05:24:45.676761660Z 05:24:45.676 [scheduled-executor-thread-2] [ERROR] i.m.m.health.indicator.HealthResult - Health indicator [redis(Primary)] reported exception: io.lettuce.core.RedisConnectionException: Unable to connect to <redacted>.redis.cache.windows.net:6379
2021-04-05T05:24:45.676794061Z io.lettuce.core.RedisConnectionException: Unable to connect to <redacted>.redis.cache.windows.net:6379
2021-04-05T05:24:45.676799261Z  at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
2021-04-05T05:24:45.676803461Z  at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
2021-04-05T05:24:45.676806761Z  at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:320)
2021-04-05T05:24:45.676829661Z  at io.lettuce.core.RedisClient.connect(RedisClient.java:211)
2021-04-05T05:24:45.676837361Z  at io.lettuce.core.RedisClient.connect(RedisClient.java:196)
2021-04-05T05:24:45.676841161Z  at io.micronaut.configuration.lettuce.health.RedisHealthIndicator.lambda$getResult$2(RedisHealthIndicator.java:98)
```

**Comment by pgressa** [comment]
The issue is not related to https://github.com/micronaut-projects/micronaut-redis/commit/398e6d5f8cbaddb3e05497c4a91ea303e12cf2d0 as @graemerocher pointed out - I have checked out the version before that fix.

It seems that it always stucks at 6th call consequent healthcheck call. There are two connection tests for Primary redis client, and on that 6th call, only 1 client connection is finished while the other one stays stucked. The health endpoint does not finishes the execution of the health checks. The healthcheck monitor task (triggered every 60s) continues to run. Proceeding with investigation.

**Comment by chrisparton1991** [comment]
That makes sense @pgressa, I have 8 cores and it was also failing after two attempts on a dual-core server.

**Comment by chrisparton1991** [comment]
Our of curiosity, were you able to glean any more information on this issue @pgressa?

I built my own simple `/health` endpoint that queries the DB and Redis, so this issue isn't blocking me.
