### ISSUE TITLE
Redis on Graal: I/O error occurred during deserialization: java.util.ArrayList; no valid constructor

### ISSUE THREAD

**Issue by j1cs** [micronaut-projects/micronaut-redis#194]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new app with: `mn create-app me.jics.backend -b maven -f graalvm,lombok,openapi,redis-lettuce,cache-ehcache -t spock`
2. Configure Redis cache as shown in the documentation 
3. Run `./mvnw package -Dpackaging=native-image`

### Expected Behaviour

after starting it should  caching the result

### Actual Behaviour

Doesn't caching anything.
With this error:
```
[lettuce-nioEventLoop-5-4] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: I/O error occurred during deserialization: java.util.ArrayList; no valid constructor
io.micronaut.core.serialize.exceptions.SerializationException: I/O error occurred during deserialization: java.util.ArrayList; no valid constructor
```

### Environment Information

- **Operating System**: Arch Linux
- **Micronaut Version:** 2.5.0
- **JDK Version:**
      
       $ native-image --version
       GraalVM 21.1.0 Java 11 CE (Java Version 11.0.11+8-jvmci-21.1-b05)

       $ java -version
        openjdk version "11.0.11" 2021-04-20
        OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
        OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Example Application

- https://github.com/j1cs/drugstore-demo/blob/master/backend/src/main/java/me/jics/StoreService.java#L42

### Complete stacktrace

```
15:32:30.361 [default-nioEventLoopGroup-1-5] INFO  me.jics.StoreController - Entering to StoreController.getAll
15:32:30.363 [lettuce-nioEventLoop-5-4] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: I/O error occurred during deserialization: java.util.ArrayList; no valid constructor
io.micronaut.core.serialize.exceptions.SerializationException: I/O error occurred during deserialization: java.util.ArrayList; no valid constructor
	at io.micronaut.core.serialize.JdkSerializer.deserialize(JdkSerializer.java:82)
	at io.micronaut.core.serialize.ObjectSerializer.deserialize(ObjectSerializer.java:109)
	at io.micronaut.core.serialize.ObjectSerializer.deserialize(ObjectSerializer.java:127)
	at io.micronaut.configuration.lettuce.cache.RedisCache$RedisAsyncCache.getWithExpire(RedisCache.java:407)
	at io.micronaut.configuration.lettuce.cache.RedisCache$RedisAsyncCache.lambda$get$0(RedisCache.java:330)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:122)
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111)
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:737)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:672)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:589)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.io.InvalidClassException: java.util.ArrayList; no valid constructor
	at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:159)
	at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:875)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2170)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
	at io.micronaut.core.serialize.JdkSerializer.deserialize(JdkSerializer.java:72)
	... 30 common frames omitted
```

**Comment by j1cs** [comment]
I was able to replicate the error in a newly created project: https://github.com/j1cs/micronaut-redis-cache-issue
I executed:
```
$ ./mvnw package -Dpackaging=native-image
[INFO] Executing: /usr/lib/jvm/java-11-graalvm/lib/svm/bin/native-image -cp  ...
```
```
$ docker-compose up
Creating redis ... done
Attaching to redis
redis    | 1:C 01 May 2021 17:09:27.724 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis    | 1:C 01 May 2021 17:09:27.724 # Redis version=6.2.2, bits=64, commit=00000000, modified=0, pid=1, just started
```
```
$ ./target/cache
13:03:40.275 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 34ms. Server Running: http://localhost:8080
```
```
$ curl http://localhost:8080/main
```
```
13:03:46.274 [default-nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for field [valueSerializer] of class: io.micronaut.configuration.lettuce.cache.DefaultRedisCacheConfiguration

Message: Error resolving field value [redis.cache.value-serializer]. Property doesn't exist or cannot be converted
Path Taken: new MainController([MainService service]) --> new $MainServiceDefinition$Intercepted(BeanContext $beanContext,Qualifier $qualifier,[List $interceptors]) --> new CacheInterceptor([CacheManager cacheManager],CacheErrorHandler errorHandler,AsyncCacheErrorHandler asyncCacheErrorHandler,ExecutorService ioExecutor,BeanContext beanContext) --> new DefaultCacheManager([List caches],Provider dynamicCacheManager) --> new RedisCache([DefaultRedisCacheConfiguration defaultRedisCacheConfiguration],RedisCacheConfiguration redisCacheConfiguration,ConversionService conversionService,BeanLocator beanLocator) --> DefaultRedisCacheConfiguration.valueSerializer
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [valueSerializer] of class: io.micronaut.configuration.lettuce.cache.DefaultRedisCacheConfiguration

Message: Error resolving field value [redis.cache.value-serializer]. Property doesn't exist or cannot be converted
Path Taken: new MainController([MainService service]) --> new $MainServiceDefinition$Intercepted(BeanContext $beanContext,Qualifier $qualifier,[List $interceptors]) --> new CacheInterceptor([CacheManager cacheManager],CacheErrorHandler errorHandler,AsyncCacheErrorHandler asyncCacheErrorHandler,ExecutorService ioExecutor,BeanContext beanContext) --> new DefaultCacheManager([List caches],Provider dynamicCacheManager) --> new RedisCache([DefaultRedisCacheConfiguration defaultRedisCacheConfiguration],RedisCacheConfiguration redisCacheConfiguration,ConversionService conversionService,BeanLocator beanLocator) --> DefaultRedisCacheConfiguration.valueSerializer
```

Hopes help.

**Comment by j1cs** [comment]
this error doesn't occur with version 3

**Comment by j1cs** [comment]
I' sorry. I was wrong the issue still persist.

**Comment by graemerocher** [comment]
I started working on this issue
