### ISSUE TITLE
Redis module doesn't connect when using native image

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-redis#202]
the api microservice won't connect to redis

```
08:11:00.617 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type [io.lettuce.core.pubsub.StatefulRedisPubSubConnection]: io.lettuce.core.pubsub.api.sync.RedisPubSubCommands.dispatch(io.lettuce.core.protocol.ProtocolKeyword, io.lettuce.core.output.CommandOutput, io.lettuce.core.protocol.CommandArgs)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.lettuce.core.pubsub.StatefulRedisPubSubConnection]: io.lettuce.core.pubsub.api.sync.RedisPubSubCommands.dispatch(io.lettuce.core.protocol.ProtocolKeyword, io.lettuce.core.output.CommandOutput, io.lettuce.core.protocol.CommandArgs)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2008)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1285)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:755)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:149)
	at io.micronaut.configuration.lettuce.session.RedisSessionStore.lambda$findRedisPubSubConnection$22(RedisSessionStore.java:405)
	at java.util.Optional.orElseGet(Optional.java:369)
	at io.micronaut.configuration.lettuce.session.RedisSessionStore.findRedisPubSubConnection(RedisSessionStore.java:405)
	at io.micronaut.configuration.lettuce.session.RedisSessionStore.<init>(RedisSessionStore.java:142)
	at io.micronaut.configuration.lettuce.session.$RedisSessionStoreDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
	at io.micronaut.session.binder.$SessionArgumentBinderDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3141)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:3044)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1062)
	at io.micronaut.context.AbstractBeanDefinition.doGetBeansOfType(AbstractBeanDefinition.java:1232)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1179)
	at io.micronaut.http.bind.$DefaultRequestBinderRegistryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
	at io.micronaut.http.server.netty.$NettyRequestArgumentSatisfierDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1264)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1014)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2770)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2756)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2427)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2401)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1285)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:755)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:149)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:73)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:311)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:297)
	at api.Application.main(Application.java:25)
Caused by: java.lang.NoSuchMethodError: io.lettuce.core.pubsub.api.sync.RedisPubSubCommands.dispatch(io.lettuce.core.protocol.ProtocolKeyword, io.lettuce.core.output.CommandOutput, io.lettuce.core.protocol.CommandArgs)
	at com.sun.proxy.$Proxy345.<clinit>(Unknown Source)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:375)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:295)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1022)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1008)
	at io.lettuce.core.RedisChannelHandler.syncHandler(RedisChannelHandler.java:314)
	at io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl.newRedisSyncCommandsImpl(StatefulRedisPubSubConnectionImpl.java:103)
	at io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl.newRedisSyncCommandsImpl(StatefulRedisPubSubConnectionImpl.java:45)
	at io.lettuce.core.StatefulRedisConnectionImpl.<init>(StatefulRedisConnectionImpl.java:81)
	at io.lettuce.core.pubsub.StatefulRedisPubSubConnectionImpl.<init>(StatefulRedisPubSubConnectionImpl.java:61)
	at io.lettuce.core.RedisClient.newStatefulRedisPubSubConnection(RedisClient.java:626)
	at io.lettuce.core.RedisClient.connectPubSubAsync(RedisClient.java:405)
	at io.lettuce.core.RedisClient.connectPubSub(RedisClient.java:328)
	at io.micronaut.configuration.lettuce.AbstractRedisClientFactory.redisPubSubConnection(AbstractRedisClientFactory.java:80)
	at io.micronaut.configuration.lettuce.DefaultRedisClientFactory.redisPubSubConnection(DefaultRedisClientFactory.java:62)
	at io.micronaut.configuration.lettuce.$DefaultRedisClientFactory$RedisPubSubConnection2Definition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1979)
```

**Comment by graemerocher** [comment]
@dstepanov if you can prioritise looking at this one. Thanks.

**Comment by ilopmar** [comment]
We have a test application for GraalVM and Redis that works: https://github.com/micronaut-graal-tests/micronaut-redis-graal

@pgressa if you are trying something different that what I'm doing in that app, please let me know or submit a PR to that app so we have that case covered

**Comment by graemerocher** [comment]
@ilopmar this app is using the `micronaut-redis-session` module which appears to exhibit the problem

**Comment by ilopmar** [comment]
I see. Then, as I said, once it's fixed, please submit a PR to the test app so we have this test covered.
